import React, { useState } from 'react';
import { Bell, ShieldAlert, CheckCircle, ArrowRight, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function Notifications() {
  const [emailAlerts, setEmailAlerts] = useState(true);
  const [pushAlerts, setPushAlerts] = useState(true);
  const [quizReleases, setQuizReleases] = useState(true);

  return (
    <div className="flex flex-col gap-6 p-1 h-[calc(100vh-7rem)] overflow-hidden">
      {/* Page Header */}
      <div className="flex justify-between items-center shrink-0">
        <div>
          <h1 className="text-xl font-black text-slate-950 dark:text-white">Notification Preferences</h1>
          <p className="text-xs font-semibold text-slate-400 dark:text-slate-500">Configure email and real-time push alert parameters for classes and quizzes</p>
        </div>
        
        <Link 
          to="/student/settings"
          className="flex items-center gap-1.5 rounded-xl border border-slate-200 px-3.5 py-1.5 text-xs font-bold text-slate-700 hover:bg-slate-50 dark:border-slate-800 dark:text-slate-350"
        >
          <ArrowLeft size={12} /> Back to Settings
        </Link>
      </div>

      {/* Preferences checkboxes list */}
      <div className="flex-1 overflow-y-auto pr-2 custom-scrollbar max-w-2xl">
        <div className="rounded-3xl border border-slate-200/50 bg-white/60 p-6 backdrop-blur-xl dark:border-slate-800/50 dark:bg-slate-900/60 shadow-sm space-y-6">
          <h3 className="text-xs font-black text-slate-400 dark:text-slate-500 uppercase tracking-wider mb-4 flex items-center gap-1.5">
            <Bell size={16} className="text-indigo-500" /> Notifications Settings
          </h3>

          <div className="space-y-4">
            {[
              { label: 'Weekly Performance Summaries', desc: 'Receive weekly report analytics generated by AI directly on your email.', value: emailAlerts, setter: setEmailAlerts },
              { label: 'Push Notifications', desc: 'Real-time alerts in browser when a teacher releases a class stream or new quiz.', value: pushAlerts, setter: setPushAlerts },
              { label: 'Quiz & Assignments Due Alerts', desc: 'Reminders 24 hours prior to homework deadlines.', value: quizReleases, setter: setQuizReleases }
            ].map((pref, idx) => (
              <div 
                key={idx} 
                className="flex items-center justify-between rounded-2xl bg-white/80 p-4 dark:bg-slate-950/80 border border-slate-100 dark:border-slate-800"
              >
                <div>
                  <h4 className="text-xs font-bold text-slate-900 dark:text-white">{pref.label}</h4>
                  <p className="text-[10px] font-semibold text-slate-500 dark:text-slate-400 mt-0.5 max-w-md">{pref.desc}</p>
                </div>

                {/* Simple Switch */}
                <button
                  type="button"
                  onClick={() => pref.setter(!pref.value)}
                  className={`relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out ${
                    pref.value ? 'bg-indigo-600' : 'bg-slate-200 dark:bg-slate-800'
                  }`}
                >
                  <span
                    className={`pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out ${
                      pref.value ? 'translate-x-5' : 'translate-x-0'
                    }`}
                  />
                </button>
              </div>
            ))}
          </div>

          <button
            onClick={() => alert('Preferences saved!')}
            className="w-full py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-black text-xs shadow-md shadow-indigo-600/10"
          >
            Save Alert Preferences
          </button>
        </div>
      </div>
    </div>
  );
}
